language: c

rvm:
  - 2.2.3

notifications:
  email: false
  slack:
    secure: hD69ZlrBGvRhr5FaglkqSgv4XPNZ6XGqsbf75/blj0U6RnYNPSfYMzfuUgcgR5I+vYJoWY5qYaAFqIgQXwExnqATr7Y+UrscLOiy7pT+/WIwIuo0TQLM0XHB50FcXksVC0xlduZIM4UlaQzMvGku5R3NTw6vnCDV9ulQzXFRzyF4yQm+e8mTnCh8lO/d5r8onPqOikTmrXM1QHDYpmP3C/EQeKuIhIUTR4hHeptv02er11z1g+JQHME4uI1GEBOSnyPDYyV/7ATPJCSKcMnVRthX82Qayl6xpu5O0iIRwPeSKykN/FvqNmona4PzcU0K/JpySHhoLhKOhPqiYV329koJuZp5RORsktbYFMfEAJx9+pKNCwWFtEghFgH5HdejEmGJ53VIDxIBG1YgJHndHichEIUZHlC86AXkD0ZUkHWGyZ3g8l64jwTKlKvxJTLux7znTKLcYT8s/czC1/tAadcuF3oQlMBCKTrttRpCwt4pDUEu9N3vaKIZIuAkEY7NsjF3QAH/t44Z4jGPGQMNE10WKeEYCqQJJYoQ73PXhdo16Xobhv6zWly7MpXgImf8KGrw/zqVmEN+SUYdp7JFesmGQyuZ0xH7wJgmxb7oQ+SPnh4mTfUrfMugnUuiyljBLFX6IBn9nO/qpD8HZno7OmF67DDV51RQS1q1NlMPWKA=

branches:
  only:
    - master
    - release
    - /^rc(\d)+-work$/

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - CC1=gcc-5
        - CXX1=g++-5
        - lto=no

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

install:
  # Based on how travis-ci works, when this is run, we are in the source
  # directory for Buffy. This means, when we go to git clone and install
  # dependencies, we need to leave that directory and then return to it when
  # done.
  # If we clone into the Buffy directory, our recursive Makefile will try to
  # build the cloned dependencies and fail
  # If we clone our dependencies into another directory using `cd` and don't
  # return to our starting directory, then our `script` step will fail because
  # its in the wrong directory.
  - export INSTALL_STARTED_AT=`pwd`
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];
    then
      brew update;
      brew install gmp; brew link --overwrite gmp;
      brew install pcre2 libressl;
      brew install llvm@3.9;
      brew link --overwrite --force llvm@3.9;
      mkdir llvmsym;
      ln -s `which llvm-config` llvmsym/llvm-config-3.9;
      ln -s `which clang++` llvmsym/clang++-3.9;
      export PATH=llvmsym/:$PATH;
    fi;
  - if [ "${TRAVIS_OS_NAME}" = "linux" ];
    then
      sudo apt-get -fy install cpuset;
      sudo apt-get install libc++-dev;
      mkdir /tmp/dl;
      cd /tmp/dl;
      wget "http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-debian8.tar.xz";
      tar -xvf clang+llvm*;
      cd clang+llvm* && sudo mkdir /tmp/llvm && sudo cp -r * /tmp/llvm/;
      sudo ln -s /tmp/llvm/bin/llvm-config /usr/local/bin/${LLVM_CONFIG};
      export PATH=/tmp/llvm/bin:$PATH;
      cd /tmp/dl;
      wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.21.tar.bz2;
      tar -xjvf pcre2-10.21.tar.bz2;
      cd pcre2-10.21 && ./configure --prefix=/usr && make && sudo make install;
      cd  /tmp/dl;
      wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz;
      tar zxvf cmake-3.5.2-Linux-x86_64.tar.gz;
      export PATH=/tmp/dl/cmake-3.5.2-Linux-x86_64/bin:$PATH;
    fi;
  - echo "Installing sendence/ponyc";
    cd /tmp;
    git clone git@github.com:Sendence/ponyc.git;
    cd ponyc;
    make CC=$CC1 CXX=$CXX1;
    sudo make install;
  - echo "Installing pony-stable";
    cd /tmp;
    git clone https://github.com/ponylang/pony-stable;
    cd pony-stable;
    git checkout 0054b429a54818d187100ed40f5525ec7931b31b;
    sudo make install;
  - echo "Installing snappy and lz4";
  - if [ "${TRAVIS_OS_NAME}" = "linux" ];
    then
      sudo apt-get install libsnappy-dev;
      cd /tmp;
      wget -O liblz4-1.7.5.tar.gz https://github.com/lz4/lz4/archive/v1.7.5.tar.gz;
      tar zxvf liblz4-1.7.5.tar.gz;
      cd lz4-1.7.5;
      sudo make install;
    fi
  - cd $INSTALL_STARTED_AT
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];
    then
      brew install erlang@18;
      brew link erlang@18 --force;
      cd /tmp;
      mkdir elixir-1.2.6;
      wget https://github.com/elixir-lang/elixir/releases/download/v1.2.6/Precompiled.zip;
      tar -xvf Precompiled.zip -C elixir-1.2.6;
      ln -s /tmp/elixir-1.2.6/bin/elixir /usr/local/bin/elixir;
      ln -s /tmp/elixir-1.2.6/bin/mix /usr/local/bin/mix;
      ln -s /tmp/elixir-1.2.6/bin/iex /usr/local/bin/iex;
      mix local.hex --force;
      mix local.rebar --force;
      cd $INSTALL_STARTED_AT;
    fi;
  - if [ "${TRAVIS_OS_NAME}" = "linux" ];
    then
      wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb;
      sudo dpkg -i erlang-solutions_1.0_all.deb;
      sudo apt-get update;
      sudo apt-get -fy install esl-erlang=1:18.3;
      kiex install 1.2.6;
      kiex use 1.2.6;
      source $HOME/.kiex/elixirs/elixir-1.2.6.env;
      mix local.hex --force;
      mix local.rebar --force;
    fi;
  - echo "Installing pytest";
    python2 -m pip install pytest==3.1.0
script:
  - make test
