version: 2
jobs:
  build:
    docker:
      - image: wallaroolabs/wallaroo-ci:2018.06.07.1
    steps:
      - checkout
      - run: make build debug=true
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify CHANGELOG.md
  integration-tests:
    docker:
      - image: wallaroolabs/wallaroo-ci:2018.06.07.1
    steps:
      - checkout
      - run: make integration-tests debug=true
  integration-tests-with-resilience:
    docker:
      - image: wallaroolabs/wallaroo-ci:2018.06.07.1
    steps:
      - checkout
      - run: make integration-tests-testing-correctness-tests-all resilience=on debug=true
  unit-tests:
    docker:
      - image: wallaroolabs/wallaroo-ci:2018.06.07.1
    steps:
      - checkout
      - run: make unit-tests debug=true
workflows:
  version: 2
  test:
    jobs:
      - build
      - verify-changelog
      - integration-tests
      - integration-tests-with-resilience
      - unit-tests
