---

  - assert:
      that:
        - item.device != ""
        - item.level != ""
        - item.components | length > 0
    with_items: software_raid_devices
    when: software_raid_devices is defined


  - assert:
      that:
        - item.mount_point != ""
        - item.filesystem_type != ""
        - item.mount_options != ""
        - item.passno != ""
        - item.dump != ""
    with_items: software_raid_devices
    when: software_raid_devices is defined and item.mount_point is defined
